import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import GNB from '@/components/GNB'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App 2',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GNB />
        {children}
      </body>
    </html>
  )
}
